### ISSUE TITLE
Riot: Legend of Runeterra is HTTPS

### ISSUE THREAD

**Issue by MathewBurnett** [uklans/cache-domains#123]
Legend of Runeterra currently downloading as HTTPS and doesn't appear to operate via the standard *.dyn.riotcdn.net redirect fallback.

This is a tracking issue. It is not yet clear if this is a temporary issue while the game is in beta or will remain the designed operation. Perhaps @v3n can shed some light on the issue.

**Comment by ciarancrocker** [comment]
Seeing no entries in normal cache access log, but requests to the following hosts during initial installation and subsequent patching:

bacon.secure.dyn.riotcdn.net
ks-foundation.secure.dyn.riotcdn.net

Looks like the bulk of the actual game download is coming from the `bacon` hostname, as once the client goes full screen to update most (if not all) SNIProxy requests are to that hostname.

**Comment by v3n** [comment]
Hmm, this is definitely not intended.

To be clear, this is the intended behavior:
1. LoR will reach out to `bacon.secure.dyn.riotcdn.net/channels/public/releases/*` over TLS to download a manifest.
2. LoR will download additional files via `bacon.dyn.riotcdn.net` utilizing the TLS downgrade where applicable.

Can you confirm whether or not you're seeing the same behavior for `ks-foundation.dyn.riotcdn.net` and 
`lol.dyn.riotcdn.net`?

More information so that we can build a repro would be super helpful:

- Is this an IPv4, IPv6, or dual stack network?
- DNS servers are set via DHCP option 6, right?
- What platform are client machines running on?
- What are the subnets of the cache and the client, respectively?

Thanks for bringing this to our attention!

**Comment by v3n** [comment]
You can disregard the above questions, I've identified the issue. :)

**Comment by Lepidopterist** [comment]
Thanks @v3n .

Let us know when you believe the issue is resolved from your end, and we'll confirm from our PoV.

**Comment by v3n** [comment]
Will do. Unfortunately, it may require a new client version which could take a week or two.

How critical would you identify this issue being? (any significant LANs upcoming, impacted PC Cafes, etc)

**Comment by Lepidopterist** [comment]
It's not a showstopper,  it's more mildly inconvenient at the moment.

We have a ~600 person LAN and a ~200 person LAN occurring on the weekend of Thurs 20th Feb - Mon 24th Feb, so it would be a 'nice to have' if it was available by then.

Thanks!

**Comment by VibroAxe** [comment]
@v3n From a UK perspective I'm aware of Westlan on the 7th (not usually high riot traffic) and then StratLAN AND Epic.Lan on the 20th (Significant cache traffic)

Cannae comment on the rest of the world.

**Comment by Lepidopterist** [comment]
Just to add to this - DreamHack Anaheim is also the same weekend (around the 22nd Feb) so having this as a target to complete by does seem to make sense.

**Comment by v3n** [comment]
Hi all,

Quick update: We're got two fixes pending for this issue.

1. A code change, which will take a few weeks to make it into LoR live due to our SDK integration timelines. This will permanently fix this issue for LoR, future games, and prevent config regressions (source of the issue here)
2. A config change, which we're targeting for 02/18. It would be ideal to do it earlier to give y'all a chance to test, but unfortunately, we're a little constrained by tech at the moment. Apologies. However, when this config goes out, it will immediately take effect globally and enable the lancache behavior again.

-- Jonathan Howard // Riot Venia

**Comment by v3n** [comment]
Apologies all, the fix for LoR (`bacon.dyn.riotcdn.net`) did not make it out for DreamHack Anaheim.

It will probably take ~2 more weeks for it to make it to live.

**Comment by MathewBurnett** [comment]
Thanks for taking the time to keep us up to date @v3n

**Comment by egguy** [comment]
There's the same problem with the LOL updater who stay in HTTPS and can't be cached.

The domain is: lol.secure.dyn.riotcdn.net

**Comment by MathewBurnett** [comment]
The LOL updater certainly can cache game content which is on lol.dye.riotcdn.net providing that your are correctly intercepting the dns. I'm watching my cache logs as i update it now

**Comment by egguy** [comment]
I think i've correctly configured the DNS: 

![image](https://user-images.githubusercontent.com/186777/75448905-5b38a380-596c-11ea-88c4-848ce36cac2f.png)

I've also added lolstatic-a.akamaihd.net to the list of intercetpted DNS but it's still using lol.secure.dyn.riotcdn.net over HTTPS. The client has been downloaded this morning.

**Comment by MathewBurnett** [comment]
@egguy if you raise a separate issue with the details of your setup perhaps we can see where we can help.

**Comment by egguy** [comment]
It's seems to be only the launcher which stay in HTTPS (1.8g update), the game client downgrade to HTTP. Sorry for the noise.

**Comment by xelaadryth** [comment]
Okay we've put in the code changes for Legends of Runeterra, if anyone wants to give this a spin!

**Comment by MathewBurnett** [comment]
This does appear to be hitting the cache 
`[riot] 10.20.60.222 / - - - [07/Mar/2022:09:23:59 +0000] "GET /channels/public/bundles/39AE50E469F896F3.bundle HTTP/1.1" 200 7008 "-" "RiotNetwork/1.0.0" "MISS" "bacon.dyn.riotcdn.net" "bytes=0-284345,328320-818291" 
`

I'm closing this and concluding that LoR now caches by HTTP as designed
