### ISSUE TITLE
New Epic domains

### ISSUE THREAD

**Issue by TheRedHerring95** [uklans/cache-domains#240]
### Describe the issue you are having
Epic appears to have picked up some new CDNs which aren't in cache-domains yet

### Describe your setup?
Client gets Adguard Home DNS via DHCP>Adguard Home directs to LANCache DNS as upstream>LANCache DNS directs to LANCache for captured domains

### Are you running sniproxy
No, not included by default in Monolithic

### DNS Configuration
No idea what Zone files are?

### New domains appear to be the following:
media-cdn.epicgames.com
cloudflare.epicgamescdn.com

I have redirected both in my Adguard Home at present, but as I'm not particularly familiar with DNS configuration, I'm not sure whether the latter is redirecting correctly, so I'm not confident in trying to fork and do a PR in case I somehow break something.

**Comment by AnthonyMaiorani** [comment]
I noticed cdn2.epicgames.com as well today

**Comment by tpill90** [comment]
I used a modified version of [epic-lancache-prefill](https://github.com/tpill90/epic-lancache-prefill) to query the API that the official Epic Launcher uses to determine which CDN it should download from.    Out of the ~80 games in my account I was able to find that some games are indeed using `cloudflare.epicgames.cdn`, and it is also **http** only.  I'd say that since the official client is using that CDN it would be a safe bet to add the domain and merge it in.

**Comment by MathewBurnett** [comment]
I have raised and merged PR #241

**Comment by MathewBurnett** [comment]
Marking this done

**Comment by lvuk-hopsoft** [comment]
I've found my epic games is using the domain:
cloudflare.epicgamescdn.com
